/* Add new boolean field for language uncertainty */
ALTER TABLE papyri.papyri ADD sprache_unsicher VARCHAR(1) DEFAULT "F" AFTER sprache;
/* Get uncertainty info from `sprache` */
UPDATE papyri.papyri SET sprache_unsicher = "T"  WHERE sprache LIKE "%?%";
/* Remove variations of (?) */
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch' WHERE `id`='60';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch' WHERE `id`='61';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch' WHERE `id`='87';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch- Griechisch' WHERE `id`='4967';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='8240';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='8246';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='8251';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='8271';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='8273';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='8275';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='8280';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='8285';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='8299';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='8320';
UPDATE `papyri`.`papyri` SET `sprache`='' WHERE `id`='8381';
UPDATE `papyri`.`papyri` SET `sprache`='' WHERE `id`='8382';
UPDATE `papyri`.`papyri` SET `sprache`='Koptisch, Arabisch' WHERE `id`='8469';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='8509';
UPDATE `papyri`.`papyri` SET `sprache`='Koptisch, Griechisch' WHERE `id`='8531';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='8629';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='8646';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='8663';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='8892';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='8893';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch' WHERE `id`='9061';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='9193';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='9362';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='10115';
UPDATE `papyri`.`papyri` SET `sprache`='Koptisch' WHERE `id`='10079';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='10116';
UPDATE `papyri`.`papyri` SET `sprache`='Demotisch/Griechisch' WHERE `id`='10926';
UPDATE `papyri`.`papyri` SET `sprache`='Lateinisch' WHERE `id`='11514';
UPDATE `papyri`.`papyri` SET `sprache`='' WHERE `id`='11909';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='11922';
UPDATE `papyri`.`papyri` SET `sprache`='' WHERE `id`='12000';
UPDATE `papyri`.`papyri` SET `sprache`='' WHERE `id`='12179';
UPDATE `papyri`.`papyri` SET `sprache`='' WHERE `id`='12597';
UPDATE `papyri`.`papyri` SET `sprache`='Demotisch' WHERE `id`='12655';
UPDATE `papyri`.`papyri` SET `sprache`='Koptisch' WHERE `id`='13264';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='13418';
UPDATE `papyri`.`papyri` SET `sprache`='Koptisch' WHERE `id`='14079';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='14247';
UPDATE `papyri`.`papyri` SET `sprache`='Koptisch' WHERE `id`='14251';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='14352';
UPDATE `papyri`.`papyri` SET `sprache`='' WHERE `id`='14421';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='14439';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='15104';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='15105';
UPDATE `papyri`.`papyri` SET `sprache`='' WHERE `id`='15998';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='16716';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch' WHERE `id`='17184';
UPDATE `papyri`.`papyri` SET `sprache`='Koptisch' WHERE `id`='17185';
UPDATE `papyri`.`papyri` SET `sprache`='Koptisch' WHERE `id`='17195';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='17196';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='17204';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='17205';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='17208';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='17211';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='17212';
UPDATE `papyri`.`papyri` SET `sprache`='G' WHERE `id`='19837';
UPDATE `papyri`.`papyri` SET `sprache`='G' WHERE `id`='19986';
UPDATE `papyri`.`papyri` SET `sprache`='G' WHERE `id`='20004';
UPDATE `papyri`.`papyri` SET `sprache`='Kopt' WHERE `id`='20008';
UPDATE `papyri`.`papyri` SET `sprache`='Kopt' WHERE `id`='20014';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch, Koptisch' WHERE `id`='20025';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch, Demotisch' WHERE `id`='20037';
UPDATE `papyri`.`papyri` SET `sprache`='G' WHERE `id`='20039';
UPDATE `papyri`.`papyri` SET `sprache`='G' WHERE `id`='20043';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch, Demotisch' WHERE `id`='20047';
UPDATE `papyri`.`papyri` SET `sprache`='G' WHERE `id`='20240';
UPDATE `papyri`.`papyri` SET `sprache`='G' WHERE `id`='20249';
UPDATE `papyri`.`papyri` SET `sprache`='G' WHERE `id`='20352';
/* Convert values from o_heid_inv */
UPDATE papyri.papyri SET sprache = "Griechisch" WHERE sprache = "G";
UPDATE papyri.papyri SET sprache = "Griechisch, Demotisch" WHERE sprache = "G, dem";
UPDATE papyri.papyri SET sprache = "Griechisch, Demotisch" WHERE sprache = "G, dem.";
UPDATE papyri.papyri SET sprache = "Koptisch" WHERE sprache = "Kopt.";
UPDATE papyri.papyri SET sprache = "Koptisch" WHERE sprache = "Kopt";
UPDATE papyri.papyri SET sprache = "Demotisch" WHERE sprache = "dem";
UPDATE papyri.papyri SET sprache = "Hieratisch" WHERE sprache = "hier";
UPDATE papyri.papyri SET sprache = "Griechisch, Demotisch" WHERE sprache = "dem - G";
/* Remove ? */
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch' WHERE `id`='385';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch' WHERE `id`='607';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch' WHERE `id`='653';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch, Koptisch' WHERE `id`='659';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch' WHERE `id`='667';
UPDATE `papyri`.`papyri` SET `sprache`='Koptisch, Arabisch' WHERE `id`='683';
UPDATE `papyri`.`papyri` SET `sprache`='Koptisch, Arabisch' WHERE `id`='684';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch' WHERE `id`='765';
UPDATE `papyri`.`papyri` SET `sprache`='Koptisch, Arabisch' WHERE `id`='966';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch, Koptisch' WHERE `id`='1093';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch, Koptisch' WHERE `id`='1094';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch' WHERE `id`='1095';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch' WHERE `id`='1231';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch, Koptisch' WHERE `id`='1382';
/* Convert '/' */
UPDATE papyri.papyri SET sprache = "Griechisch, Koptisch, Arabisch" WHERE id = "8257";
UPDATE papyri.papyri SET sprache = "Griechisch, Arabisch" WHERE id = "8258";
UPDATE papyri.papyri SET sprache = "Griechisch, Koptisch" WHERE id = "8319";
UPDATE papyri.papyri SET sprache = "Griechisch, Koptisch" WHERE id = "8338";
UPDATE papyri.papyri SET sprache = "Koptisch, Griechisch" WHERE id = "8353";
UPDATE papyri.papyri SET sprache = "Koptisch, Griechisch" WHERE id = "8364";
UPDATE papyri.papyri SET sprache = "Koptisch, Griechisch\n" WHERE id = "8407";
UPDATE papyri.papyri SET sprache = "Koptisch, Griechisch" WHERE id = "8484";
UPDATE papyri.papyri SET sprache = "Koptisch, Arabisch" WHERE id = "8592";
UPDATE papyri.papyri SET sprache = "Koptisch, Griechisch\n" WHERE id = "8665";
UPDATE papyri.papyri SET sprache = "Koptisch, Griechisch" WHERE id = "8666";
UPDATE papyri.papyri SET sprache = "Griechisch, Koptisch, Arabisch" WHERE id = "8716";
UPDATE papyri.papyri SET sprache = "Griechisch, Koptisch, Arabisch" WHERE id = "8717";
UPDATE papyri.papyri SET sprache = "Arabisch, Koptisch, Griechisch" WHERE id = "8744";
UPDATE papyri.papyri SET sprache = "Koptisch, Arabisch" WHERE id = "8948";
UPDATE papyri.papyri SET sprache = "Koptisch, Arabisch\n" WHERE id = "8949";
UPDATE papyri.papyri SET sprache = "Koptisch, Arabisch" WHERE id = "8950";
UPDATE papyri.papyri SET sprache = "Koptisch, Arabisch" WHERE id = "8951";
UPDATE papyri.papyri SET sprache = "Koptisch, Arabisch" WHERE id = "8952";
UPDATE papyri.papyri SET sprache = "Koptisch, Arabisch" WHERE id = "8953";
UPDATE papyri.papyri SET sprache = "Koptisch, Arabisch, Griechisch" WHERE id = "9202";
UPDATE papyri.papyri SET sprache = "Koptisch, Griechisch" WHERE id = "9218";
UPDATE papyri.papyri SET sprache = "Koptisch, Arabisch" WHERE id = "9461";
UPDATE papyri.papyri SET sprache = "Koptisch, Arabisch" WHERE id = "9472";
UPDATE papyri.papyri SET sprache = "Koptisch, Arabisch" WHERE id = "9473";
UPDATE papyri.papyri SET sprache = "Koptisch, Arabisch" WHERE id = "9474";
UPDATE papyri.papyri SET sprache = "Koptisch, Arabisch" WHERE id = "9475";
UPDATE papyri.papyri SET sprache = "Koptisch, Arabisch" WHERE id = "9617";
UPDATE papyri.papyri SET sprache = "Koptisch, Arabisch" WHERE id = "10031";
UPDATE papyri.papyri SET sprache = "Koptisch, Arabisch" WHERE id = "10071";
UPDATE papyri.papyri SET sprache = "Koptisch, Arabisch" WHERE id = "10088";
UPDATE papyri.papyri SET sprache = "Koptisch, Griechisch" WHERE id = "10121";
UPDATE papyri.papyri SET sprache = "Demotisch, Griechisch" WHERE id = "10737";
UPDATE papyri.papyri SET sprache = "Demotisch, Griechisch" WHERE id = "10926";
UPDATE papyri.papyri SET sprache = "Demotisch, Griechisch" WHERE id = "10941";
UPDATE papyri.papyri SET sprache = "Griechisch, Lateinisch" WHERE id = "11349";
UPDATE papyri.papyri SET sprache = "Griechisch, Koptisch" WHERE id = "11440";
UPDATE papyri.papyri SET sprache = "Griechisch, Demotisch" WHERE id = "11681";
UPDATE papyri.papyri SET sprache = "Demotisch, Griechisch" WHERE id = "11682";
UPDATE papyri.papyri SET sprache = "Griechisch, Demotisch" WHERE id = "11683";
UPDATE papyri.papyri SET sprache = "Griechisch, Demotisch" WHERE id = "11685";
UPDATE papyri.papyri SET sprache = "Griechisch, Demotisch" WHERE id = "11810";
UPDATE papyri.papyri SET sprache = "Griechisch, Arabisch" WHERE id = "11958";
UPDATE papyri.papyri SET sprache = "Griechisch, Arabisch" WHERE id = "11959";
UPDATE papyri.papyri SET sprache = "Griechisch, Arabisch" WHERE id = "11960";
UPDATE papyri.papyri SET sprache = "Griechisch, Koptisch" WHERE id = "12203";
UPDATE papyri.papyri SET sprache = "Griechisch, Demotisch" WHERE id = "12874";
UPDATE papyri.papyri SET sprache = "Griechisch, Demotisch" WHERE id = "12992";
UPDATE papyri.papyri SET sprache = "Griechisch, Demotisch" WHERE id = "13829";
UPDATE papyri.papyri SET sprache = "Griechisch, Arabisch" WHERE id = "13873";
UPDATE papyri.papyri SET sprache = "Demotisch, Griechisch" WHERE id = "13969";
UPDATE papyri.papyri SET sprache = "Griechisch, Koptisch" WHERE id = "14641";
UPDATE papyri.papyri SET sprache = "Griechisch, Demotisch" WHERE id = "17125";
UPDATE papyri.papyri SET sprache = "Griechisch, Arabisch" WHERE id = "17316";
UPDATE papyri.papyri SET sprache = "Lateinisch, Griechisch" WHERE id = "17318";
UPDATE papyri.papyri SET sprache = "Lateinisch, Griechisch" WHERE id = "17319";
UPDATE papyri.papyri SET sprache = "Griechisch, Syrisch" WHERE id = "17322";
/* Convert '-' */
UPDATE papyri.papyri SET sprache = "Arabisch" WHERE id = "121";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "135";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "147";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "148";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "152";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "165";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "166";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "180";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "201";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "204";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "220";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "222";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "226";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "233";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "235";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "237";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "243";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "244";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "247";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "275";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "280";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "289";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "290";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechich" WHERE id = "303";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "308";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "315";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "326";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "331";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "358";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "363";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "365";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "395";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "397";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "403";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "774";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "805";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "812";
UPDATE papyri.papyri SET sprache = "Arabisch" WHERE id = "853";
UPDATE papyri.papyri SET sprache = "Arabisch" WHERE id = "858";
UPDATE papyri.papyri SET sprache = "Arabisch, Griechisch" WHERE id = "4967";
UPDATE papyri.papyri SET sprache = "Griechisch, Koptisch" WHERE id = "11529";
UPDATE papyri.papyri SET sprache = "Koptisch, Griechisch" WHERE id = "12517";
UPDATE papyri.papyri SET sprache = "Griechisch, Koptisch" WHERE id = "13114";
/* Remove trailing newlines */
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch, Griechisch' WHERE `id`='125';
UPDATE `papyri`.`papyri` SET `sprache`='Koptisch, Griechisch' WHERE `id`='8407';
UPDATE `papyri`.`papyri` SET `sprache`='Koptisch, Arabisch' WHERE `id`='8949';
UPDATE `papyri`.`papyri` SET `sprache`='Koptisch, Griechisch' WHERE `id`='8665';
UPDATE `papyri`.`papyri` SET `sprache`='Griechisch' WHERE `id`='16885';
/* Convert 'vermutlich, 'möglicherweise', ... */
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch', `sprache_unsicher`='T' WHERE `id`='47';
UPDATE `papyri`.`papyri` SET `sprache`='', `sprache_unsicher`='T' WHERE `id`='91';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch', `sprache_unsicher`='T' WHERE `id`='163';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch', `sprache_unsicher`='T' WHERE `id`='179';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch', `sprache_unsicher`='T' WHERE `id`='418';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch', `sprache_unsicher`='T' WHERE `id`='445';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch', `sprache_unsicher`='T' WHERE `id`='446';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch', `sprache_unsicher`='T' WHERE `id`='550';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch', `sprache_unsicher`='T' WHERE `id`='551';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch', `sprache_unsicher`='T' WHERE `id`='552';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch', `sprache_unsicher`='T' WHERE `id`='624';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch', `sprache_unsicher`='T' WHERE `id`='640';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch', `sprache_unsicher`='T' WHERE `id`='718';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch', `sprache_unsicher`='T' WHERE `id`='743';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch', `sprache_unsicher`='T' WHERE `id`='1116';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch', `sprache_unsicher`='T' WHERE `id`='1248';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch', `sprache_unsicher`='T' WHERE `id`='1344';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch', `sprache_unsicher`='T' WHERE `id`='1612';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch, Griechisch' WHERE `id`='763';
UPDATE `papyri`.`papyri` SET `sprache`='Arabisch', `sprache_unsicher`='T' WHERE `id`='63';
/* Make sprache a web2py list field */
UPDATE papyri.papyri SET sprache = CONCAT("|", REPLACE(sprache, ", ", "|"), "|");
