if False:
	from gluon import *
	from db import Field, define_table
	import db

db.define_table("seiten",
	# DB-Infos
	Field("project_id", type="string", label="DWork-Projekt-ID", length="25"),
	Field("fb", type="string", label="Front/Back", writable=False, length="2"),
	# Historisch: Seiten-Infos
	Field("rv", type="string", label="RV", length="128"),
	Field("andere_seite", type="string", label="Andere Seite", length="128"),
	# Publikation
	Field("originaltitel", type="text", label="Originaltitel"),
	Field("band", type="integer", label="Band"),
	Field("zus_band", type="string", label="Zusatz Band", length="512"),
	Field("nummer", type="string", label="Nummer", length="32"),
	Field("bl", type="string", label="BL", length="256"),
	Field("seite", type="string", label="Seite", length="32"),
	Field("ldab", type="integer", label="LDAB-Nummer"),
	Field("pack2", type="integer", label="Pack-Nummer"),
	Field("abbildung", type="string", label="Gedruckte Abbildung", length="512"),
	Field("andere_berichtigungen", type="string", label="Andere Berichtigungen", length="512"),
	Field("andere_publikation", type="string", label="Papyrologische Reihen", length="512"),
	Field("literatur", type="string", label="Sekundärliteratur", length="32"),
	Field("pub_sonst", type="string", label="Publikation: Verstreute", length="512"),
	Field("publ_erg", type="string", label="Publikation: Ergänzung", length="64"),
	Field("publikation", type="string", label="Publikation: Reihentitel", length="512"),
	Field("andere_links", type="list:string", label="Generische Links"),
	Field("tm_nummer", type="string", label="Trismegistos-Nummer", length="64"),
	Field("papyri_info", type="list:string", label="DDB-Hybrid"),
	Field("art", type="string", label="Textinfo: Art", length="128"),
	Field("art_1", type="string", label="Textinfo: Art 1", length="64"),
	Field("art_2", type="string", label="Textinfo: (Art 2) Genauere Beschreibung", length="256"),
	Field("inhalt", type="text", label="Inhalt des Textes"),
	Field("schrift", type="string", label="Schrift", length="64"),
	Field("ort", type="string", label="Abfassungsort des Textes", length="128"),
	Field("palaeographisches", type="text", label="Paläographie"),
	# Datierung
	Field("erwaehnte_daten", type="string", label="", length="512"),
	Field("wochentag", type="string", label="", length="32"),
	Field("t1", type="integer", label="Tag von"),
	Field("m1", type="integer", label="Monat von"),
	Field("j1", type="integer", label="Jahr von"),
	Field("jh1", type="integer", label="Jhdt. von"),
	Field("erg1", type="string", label="Erg. von", length="64"),
	Field("t2", type="integer", label="Tag bis"),
	Field("m2", type="integer", label="Monat bis"),
	Field("j2", type="integer", label="Jahr bis"),
	Field("jh2", type="integer", label="Jhdt. bis"),
	Field("erg2", type="string", label="Erg. bis", length="32"),
	Field("t1hig", type="string", label="Tag von (H)", length="64"),
	Field("m1hig", type="string", label="Monat von (H)", length="64"),
	Field("j1hig", type="integer", label="Jahr von (H)"),
	Field("jh1hig", type="integer", label="Jhdt. von (H)"),
	Field("erg1hig", type="string", label="Erg. bis (H)", length="32"),
	Field("t2hig", type="string", label="Tag bis (H)", length="512"),
	Field("m2hig", type="string", label="Monat bis (H)", length="64"),
	Field("j2hig", type="integer", label="Jahr bis (H)"),
	Field("jh2hig", type="integer", label="Jhdt. bis (H)"),
	Field("erg2hig", type="string", label="Erg. von (H)", length="32"),
	Field("unsicher", type="string", label="Datierung unsicher", length="32"),
	Field("zusatz", type="string", label="Datierung: Zusatz", length="32"),
	Field("zusaetzlich", type="string", label="Datierung: Zusätzlich", length="32"),
	Field("bemerkungen", type="text", label="Bemerkungen"),
	Field("bild_importiert", type="boolean", label="Bildimport"),
	Field("fertig", type="boolean", label="", length="32"),
	Field("link_abb", type="string", label="Link Abb.", length="32"),
	Field("mehrfach", type="string", label="Mehrfach", length="32"),
	Field("neu", type="boolean", label="Neu?"),
	Field("titel", type="string", label="Titel", length="512"),
	Field("url_abb", type="string", label="URL Abb.", length="512"),
	# Interne Infos: Bearbeitungsstatus
	Field("status", type="string", label="Status", length="128"),
	Field("bearb", type="boolean", label="bearb.?", length="4"),
	Field("bearb_zusatz", type="string", label="bearb_zusatz"),
	Field("bearbeiter", type="string", label="Bearbeiter", length="512"),
	# Interne Infos: Photoarchiv
	Field("alte_aufnahme", type="string", label="alte Aufnahme", length="512"),
	Field("negativ", type="string", label="Negativ"),
	Field("photo_an", type="text", label="Photo an"),
	Field("tiff_600_dpi", type="string", label="TIFF (600 dpi)"),
	Field("jpeg_150_dpi", type="string", label="JPEG (150 dpi)"),
	Field("jpeg_72_dpi", type="string", label="JPEG (72 dpi)"),
	# Objektdetails
	Field("rueckseite", type="string", label="Rückseite", length="64"),
	Field("sprache", type="list:string", label="Sprache", length="128"),
	Field("erhaltungszustand", type="text", label="Erhaltungszustand"),
	Field("bem_rest", type="string", label="Bemerkungen zur Restaurierung", length="512"),
	# Sonstiges
	Field("eingegeben_am", type="date", label="eingegeben am", length="32", writable=False, default=request.now),
	Field("zuletzt_geaendert_am", type="date", label="zuletzt geändert am", length="32", writable=False, default=request.now, update=request.now),
	migrate=False
)


db.define_table("papyri",
	# Inventarisierung
	Field("project_id", type="string", label="DWork-Projekt-ID", length="25"),
	Field("front_id", type=db.seiten, label="Vorderseite"),
	Field("back_id", type=db.seiten, label="Rückseite"),
	Field("heid_inv_cat", type="string", label="Inv.: Kategorie", length="1"),
	Field("heid_inv_spr", type="string", label="Inv.: Sprache", length="64"),
	Field("heid_inv_nr", type="integer", label="Inv.: Nummer", length="16"),
	Field("heid_inv_buchstabe", type="string", label="Inv.: Buchstabe", length="128"),
	Field("heid_inv", type="string", label="Inv. komplett", length="128"),
	Field("eigenart", type="string", label="Eigenart"),
	Field("gerahmte_nummer", type="string", label="gerahmte Nummer", length="16"),
	# Erwerbung
	Field("herkunft", type="string", label="Herkunft", length="256"),
	Field("fundort", type="string", label="Fundort", length="64"),
	Field("notiz", type="string", label="Notiz", length="500"),
	Field("erworben_durch_name", type="string", label="erworben durch: Name", length="256"),
	Field("erworben_durch_monat", type="string", label="erworben durch: Monat", length="32"),
	Field("erworben_durch_jahr", type="string", label="erworben durch: Jahr", length="32"),
	Field("erw_bem", type="string", label="Erw. Bem.", length="256"),
	# Objektdetails
	Field("breite", type="list:string", label="Breite"),
	Field("hoehe", type="list:string", label="Höhe"),
	Field("material", type="string", label="Material", length="64"),
	# Sonstiges
	Field("zusammensetzung_info", type="string", label="Informationen zur Zusammensetzung"),
	Field("fragmentangabe", type="string", label="Fragmentangabe"),
	Field("katalogisierung", type="string", label="Katalogisierung", length="64"),
	Field("ausleihe", type="string", label="Informationen zur Ausleihe", length=512),
	Field("vorhanden_fehlt", type="string", label="Vorhanden/Fehlt"),
	Field("eingegeben_am", type="date", label="eingegeben am", length="32", writable=False, default=request.now),
	Field("zuletzt_geaendert_am", type="date", label="zuletzt geändert am", length="32", writable=False, default=request.now, update=request.now),
	migrate=False
)
